Breed/orches relpath
BRReed/scripts pull request #6
Opened 2023-11-16 03:15 UTC by BRReed

tell your friends if they want to teach me differently they can hire me

2023-11-17 04:51 UTC, stephenlauck requested changes

2023-11-17 04:51 UTC, stephenlauck commented on .gitignore
> +vm-management/images/
The default place to put libvirt images is in `/var/lib/libvirt/images`.

2023-11-17 04:51 UTC, stephenlauck commented on orchestration/node-apps/hello-world/spin-up-hw-app.sh
> +  export VM=jammy-cloud; curl https://raw.githubusercontent.com/BRReed/scripts/main/vm-management/ubuntu/spin-up-jammy.sh | bash && while ( ! ssh -t -o StrictHostKeyChecking=no brian@$(virsh domifadd
The point of using an environment variable is that you can set it outside of the script to make the script more flexible. You would put this export in front of running the script not inside it.

2023-11-17 04:51 UTC, stephenlauck commented on orchestration/node-apps/hello-world/spin-up-hw-app.sh
> +  ssh -q brian@$(virsh domifaddr jammy-cloud | awk -F'[ /]+' '{if (NR>2) print $5}') 'curl https://raw.githubusercontent.com/BRReed/scripts/main/get-docker/ubuntu/get-docker.sh | bash'
:+1:

2023-11-17 04:51 UTC, stephenlauck commented on orchestration/node-apps/hello-world/spin-up-hw-app.sh
> +if ( ssh -q brian@$(virsh domifaddr jammy-cloud | awk -F'[ /]+' '{if (NR>2) print $5}') [ -f ./Dockerfile ] )
maybe use `stat` here instead of the bracket style.

2023-11-17 04:51 UTC, stephenlauck commented on orchestration/node-apps/hello-world/spin-up-hw-app.sh
> +  ssh -q brian@$(virsh domifaddr jammy-cloud | awk -F'[ /]+' '{if (NR>2) print $5}') "curl -o ./Dockerfile https://raw.githubusercontent.com/BRReed/hello-relativepath/main/scripts/docker/hello-world-
:+1: I like it.

2023-11-17 04:51 UTC, stephenlauck commented on orchestration/node-apps/hello-world/spin-up-hw-app.sh
> +if ( ssh -q brian@$(virsh domifaddr jammy-cloud | awk -F'[ /]+' '{if (NR>2) print $5}') [ -f ./package.json ] )
same, try stat maybe instead, but the -f might be ok, but maybe use `test -f package.json`?

2023-11-17 04:51 UTC, stephenlauck commented on orchestration/node-apps/hello-world/spin-up-hw-app.sh
> +  ssh -q brian@$(virsh domifaddr jammy-cloud | awk -F'[ /]+' '{if (NR>2) print $5}') "curl -o ./package.json https://raw.githubusercontent.com/BRReed/hello-relativepath/main/scripts/docker/hello-worl
So you shouldn't be doing all these one time file puts via curl, just make a script that does all this and run just that script...? So it's like `node_deploy.sh` and does the last 3 curls for you instead of all these single ssh commands, put them all in one script and run that.

2023-11-17 04:51 UTC, stephenlauck commented on orchestration/node-apps/hello-world/spin-up-hw-app.sh
> +  ssh -q brian@$(virsh domifaddr jammy-cloud | awk -F'[ /]+' '{if (NR>2) print $5}') "curl -o ./hello-world-app.js https://raw.githubusercontent.com/BRReed/hello-relativepath/main/hello-world-app.js"
Same here, just put this all in one script.

2023-11-17 04:51 UTC, stephenlauck commented on orchestration/node-apps/hello-world/spin-up-hw-app.sh
> +  ssh -q brian@$(virsh domifaddr jammy-cloud | awk -F'[ /]+' '{if (NR>2) print $5}') "curl https://raw.githubusercontent.com/BRReed/scripts/main/nodejs-management/install-start/ubuntu/install-start.s
Maybe put all the previous commands in this one. Also you should create a systemd service file for your node app instead of running it like this. Then make sure your service is running and enabled.

2023-11-17 04:51 UTC, stephenlauck commented on vm-management/ubuntu/destroy-jammy.sh
> +if !(virsh list --all | grep " ${VM} ") then
It's less important to wrap destroy/delete in conditionals, just remove all the if statements in here and just run the commands to delete. I can explain why if we chat.

2023-11-17 04:51 UTC, stephenlauck commented on vm-management/ubuntu/spin-up-jammy.sh
> +  - name: brian
maybe just make this $USER all through the script or make it a envar like $VM_USER?

2023-11-17 04:51 UTC, stephenlauck commented on vm-management/ubuntu/spin-up-jammy.sh
> +  curl --create-dirs -o ~/spaghetti/scripts/vm-management/images/jammy-server-cloudimg-amd64.img https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img
Put these in `/var/lib/libvirt/images`.

https://wiki.libvirt.org/Tips.html#adding-an-alternative-storage-pool

2023-11-17 22:17 UTC, stephenlauck requested changes

2023-11-17 22:17 UTC, stephenlauck commented on vm-management/ubuntu/destroy-jammy.sh
> +rm user-data
Why not do it all with &&?

2023-11-17 22:17 UTC, stephenlauck commented on orchestration/node-apps/hello-world/node-deploy.sh
> +if ( ssh -q brian@$(virsh domifaddr jammy-cloud | awk -F'[ /]+' '{if (NR>2) print $5}') "stat ./Dockerfile" )
No, what I mean was put all these commands in one script and then just remote run that script. Not put all the remote commands in a script and then remote run each command.

2023-11-17 23:32 UTC, BRReed commented on orchestration/node-apps/hello-world/node-deploy.sh
> +if ( ssh -q brian@$(virsh domifaddr jammy-cloud | awk -F'[ /]+' '{if (NR>2) print $5}') "stat ./Dockerfile" )
i had already changed it by the time you looked at this. didnt think you'd be actively checking until i asked for another review

2023-11-18 02:18 UTC, stephenlauck requested changes

2023-11-18 02:18 UTC, stephenlauck commented on orchestration/node-apps/hello-world/spin-up-hw-app.sh
> +  ssh -q brian@$(virsh domifaddr jammy-cloud | awk -F'[ /]+' '{if (NR>2) print $5}') "curl https://raw.githubusercontent.com/BRReed/scripts/breed/orches-relpath/orchestration/node-apps/hello-world/no
Create a systemd service for this instead of piping to bash&. 

https://nodesource.com/blog/running-your-node-js-app-with-systemd-part-1/

2023-11-18 06:35 UTC, BRReed commented on orchestration/node-apps/hello-world/spin-up-hw-app.sh
> +  ssh -q brian@$(virsh domifaddr jammy-cloud | awk -F'[ /]+' '{if (NR>2) print $5}') "curl https://raw.githubusercontent.com/BRReed/scripts/breed/orches-relpath/orchestration/node-apps/hello-world/no
I still need to fix the spin-up-jammy cloud init file. everything else I think is good.

2023-11-20 01:04 UTC, stephenlauck commented on orchestration/node-apps/hello-world/node-deploy.sh
> +  npm install
I've seen the install and run just put inside the system service.

2023-11-20 01:04 UTC, stephenlauck commented on orchestration/node-apps/hello-world/node-deploy.sh
> +  sudo systemctl start hello-relpath.service
use `is-active` and `is-enabled` to do assertions and then take actions like `sudo systemctl restart` or `enable`.

2023-11-20 06:15 UTC, stephenlauck approved these changes
:shipit:

2023-11-20 21:28 UTC, merged